-- AlterTable
ALTER TABLE "public"."Report" ADD COLUMN     "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "name" TEXT NOT NULL DEFAULT 'report',
ALTER COLUMN "document" SET NOT NULL,
ALTER COLUMN "document" SET DATA TYPE TEXT;
